#!/bin/bash

# Link to the binary
ln -sf '/opt/Vysor/vysorapp' '/usr/bin/vysorapp'

# SUID chrome-sandbox for Electron 5+
chmod 4755 '/opt/Vysor/chrome-sandbox' || true

update-mime-database /usr/share/mime || true
update-desktop-database /usr/share/applications || true
